//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Resources.MessagesResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATR.Common.Resources.MessagesResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the selected documents have been acknowledged.
        /// </summary>
        public static string acknowledgmentSuccess {
            get {
                return ResourceManager.GetString("acknowledgmentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check if the user is the last administrator of his entity.
        /// </summary>
        public static string checkErrorLastAdmin {
            get {
                return ResourceManager.GetString("checkErrorLastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting the {0}, some users are still attached to this application.
        /// </summary>
        public static string dataDeleteEntityNewApplicationUsedError {
            get {
                return ResourceManager.GetString("dataDeleteEntityNewApplicationUsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the {0}.
        /// </summary>
        public static string dataDeleteError {
            get {
                return ResourceManager.GetString("dataDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete Entity: some users still belong to this entity.
        /// </summary>
        public static string dataDeleteErrorEntityUsers {
            get {
                return ResourceManager.GetString("dataDeleteErrorEntityUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last user administrator of his entity. Are you sure to delete this user?.
        /// </summary>
        public static string dataDeleteLastEntityAdministrator {
            get {
                return ResourceManager.GetString("dataDeleteLastEntityAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted with success.
        /// </summary>
        public static string dataDeleteSuccess {
            get {
                return ResourceManager.GetString("dataDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted from database.
        /// </summary>
        public static string dataDeleteUserSuccess {
            get {
                return ResourceManager.GetString("dataDeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user to {0} group in the AD. Unable to update user..
        /// </summary>
        public static string dataErrorAddUserToGroupAD {
            get {
                return ResourceManager.GetString("dataErrorAddUserToGroupAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Business Type must be different than NONE.
        /// </summary>
        public static string dataErrorEntityBusinessTypeNone {
            get {
                return ResourceManager.GetString("dataErrorEntityBusinessTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Business Type is Prospect, the validity end date must be filled.
        /// </summary>
        public static string dataErrorEntityBusinessTypeValidityEndDate {
            get {
                return ResourceManager.GetString("dataErrorEntityBusinessTypeValidityEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the Entity. CRM code already used.
        /// </summary>
        public static string dataErrorEntityCrmCode {
            get {
                return ResourceManager.GetString("dataErrorEntityCrmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the Entity. The company name is already used.
        /// </summary>
        public static string dataErrorEntityName {
            get {
                return ResourceManager.GetString("dataErrorEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency must be selected if a notification is checked.
        /// </summary>
        public static string dataErrorFrequencyNotSelected {
            get {
                return ResourceManager.GetString("dataErrorFrequencyNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove user from {0} group in the AD. Unable to update user..
        /// </summary>
        public static string dataErrorRemoveUserFromGroupAD {
            get {
                return ResourceManager.GetString("dataErrorRemoveUserFromGroupAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with ATR access is allowed only if the user have My Requests Status Access.
        /// </summary>
        public static string dataErrorUserAccessRightsInteractionWithATR {
            get {
                return ResourceManager.GetString("dataErrorUserAccessRightsInteractionWithATR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove the last user administrator of the Entity.
        /// </summary>
        public static string dataErrorUserLastAdmin {
            get {
                return ResourceManager.GetString("dataErrorUserLastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file must have a .xlsx format.
        /// </summary>
        public static string dataExcelFileUploadFormatError {
            get {
                return ResourceManager.GetString("dataExcelFileUploadFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters &apos;&lt;&apos; and &apos;&gt;&apos; are not allowed.
        /// </summary>
        public static string dataForbiddenSuperiorInferiorCharaters {
            get {
                return ResourceManager.GetString("dataForbiddenSuperiorInferiorCharaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the search form for {0}.
        /// </summary>
        public static string dataGetSearchError {
            get {
                return ResourceManager.GetString("dataGetSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded image must have a .jpg, .jpeg or .png format.
        /// </summary>
        public static string dataImageUploadFormatError {
            get {
                return ResourceManager.GetString("dataImageUploadFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file smaller than 16 Ko.
        /// </summary>
        public static string dataImageUploadSizeError {
            get {
                return ResourceManager.GetString("dataImageUploadSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email address is incorrect.
        /// </summary>
        public static string dataIncorrectEmail {
            get {
                return ResourceManager.GetString("dataIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is incorrect.
        /// </summary>
        public static string dataIncorrectFormat {
            get {
                return ResourceManager.GetString("dataIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is incorrect.
        /// </summary>
        public static string dataIncorrectPhoneNumber {
            get {
                return ResourceManager.GetString("dataIncorrectPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the {0}.
        /// </summary>
        public static string dataInsertError {
            get {
                return ResourceManager.GetString("dataInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the {0}: Entity must have My Request Status Access before adding Interaction With ATR access.
        /// </summary>
        public static string dataInsertErrorEntityApplicationAccess {
            get {
                return ResourceManager.GetString("dataInsertErrorEntityApplicationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the {0}: No checkbox selected.
        /// </summary>
        public static string dataInsertErrorEntityWarehouse {
            get {
                return ResourceManager.GetString("dataInsertErrorEntityWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the user account in the AD. Unable to update user..
        /// </summary>
        public static string dataInsertErrorUserAD {
            get {
                return ResourceManager.GetString("dataInsertErrorUserAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inserted with success.
        /// </summary>
        public static string dataInsertSuccess {
            get {
                return ResourceManager.GetString("dataInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be longer than {1} characters.
        /// </summary>
        public static string dataLengthError {
            get {
                return ResourceManager.GetString("dataLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0}.
        /// </summary>
        public static string dataLoadError {
            get {
                return ResourceManager.GetString("dataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Frequency is required if a Notification is selected.
        /// </summary>
        public static string dataMandatoryFrequencyError {
            get {
                return ResourceManager.GetString("dataMandatoryFrequencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot find the {0} (id={1}) in the database.
        /// </summary>
        public static string dataNotFoundError {
            get {
                return ResourceManager.GetString("dataNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file must have a .pdf format.
        /// </summary>
        public static string dataPdfFileUploadFormatError {
            get {
                return ResourceManager.GetString("dataPdfFileUploadFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required.
        /// </summary>
        public static string dataRequiredError {
            get {
                return ResourceManager.GetString("dataRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to search data for {0}.
        /// </summary>
        public static string dataSearchError {
            get {
                return ResourceManager.GetString("dataSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the {0}.
        /// </summary>
        public static string dataUpdateError {
            get {
                return ResourceManager.GetString("dataUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unabled to update the {0}: Entity must have My Request Status Access before adding Interaction With ATR access.
        /// </summary>
        public static string dataUpdateErrorEntityApplicationAccess {
            get {
                return ResourceManager.GetString("dataUpdateErrorEntityApplicationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the {0}: No user admin is set, cannot edit the entity.
        /// </summary>
        public static string dataUpdateErrorEntityUserAdmin {
            get {
                return ResourceManager.GetString("dataUpdateErrorEntityUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot define more than {0} validated users as {1}.
        /// </summary>
        public static string dataUpdateErrorRightNbUser {
            get {
                return ResourceManager.GetString("dataUpdateErrorRightNbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot grant {0} rights if {1} is not selected.
        /// </summary>
        public static string dataUpdateErrorRightsDependency {
            get {
                return ResourceManager.GetString("dataUpdateErrorRightsDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated with success.
        /// </summary>
        public static string dataUpdateSuccess {
            get {
                return ResourceManager.GetString("dataUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update user&apos;s informations in AD.
        /// </summary>
        public static string dataUpdateUserAD {
            get {
                return ResourceManager.GetString("dataUpdateUserAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload data for {0}.
        /// </summary>
        public static string dataUploadError {
            get {
                return ResourceManager.GetString("dataUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data uploaded with success.
        /// </summary>
        public static string dataUploadSuccess {
            get {
                return ResourceManager.GetString("dataUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty.
        /// </summary>
        public static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file must have an excel file format (.xls or .xlsx).
        /// </summary>
        public static string excelFormatError {
            get {
                return ResourceManager.GetString("excelFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting add form for new {0}.
        /// </summary>
        public static string formInsertError {
            get {
                return ResourceManager.GetString("formInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting edit form for new {0} (id={1}).
        /// </summary>
        public static string formUpdateError {
            get {
                return ResourceManager.GetString("formUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No only white space allowed.
        /// </summary>
        public static string isOnlyWhiteSpaceError {
            get {
                return ResourceManager.GetString("isOnlyWhiteSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is not valid.
        /// </summary>
        public static string modelNotValid {
            get {
                return ResourceManager.GetString("modelNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not defined.
        /// </summary>
        public static string notDefined {
            get {
                return ResourceManager.GetString("notDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of groups requested is higher than the number of groups possible..
        /// </summary>
        public static string numberGroupNotValid {
            get {
                return ResourceManager.GetString("numberGroupNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the {0}: {1}.
        /// </summary>
        public static string updateBaseErrorMessage {
            get {
                return ResourceManager.GetString("updateBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to update the user.
        /// </summary>
        public static string userNotAllowedToUpdate {
            get {
                return ResourceManager.GetString("userNotAllowedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version entered is not valid.
        /// </summary>
        public static string versionNotValid {
            get {
                return ResourceManager.GetString("versionNotValid", resourceCulture);
            }
        }
    }
}
