//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACS_PDF_FILE
    {
        public string ACS_FILENAME { get; set; }
        public int ACS_FILESIZE { get; set; }
        public byte[] ACS_FILECONTENT { get; set; }
        public string ACS_ZONE { get; set; }
        public System.DateTime ACS_DATEMODIF { get; set; }
    }
}
