//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACS_ZONE2
    {
        public string ACS_NUMPN { get; set; }
        public string ACS_LIB { get; set; }
        public string ACS_COM { get; set; }
        public string ACS_NOMFIC { get; set; }
        public string ACS_PXECHSTD { get; set; }
        public string ACS_CUR_ECHSTD { get; set; }
        public string ACS_PXREPSTD { get; set; }
        public string ACS_CUR_REPSTD { get; set; }
        public string ACS_PXREPMAJ { get; set; }
        public string ACS_CUR_REPMAJ { get; set; }
        public string ACS_PXOVERHAUL { get; set; }
        public string ACS_CUR_OVERHAUL { get; set; }
        public string ACS_PXTEST { get; set; }
        public string ACS_CUR_TEST { get; set; }
        public string ACS_PXSCRAP { get; set; }
        public string ACS_CUR_SCRAP { get; set; }
        public string ACS_ZONE { get; set; }
        public string ACS_SPT_REPSTD { get; set; }
        public string ACS_SPT_REPMAJ { get; set; }
        public string ACS_SPT_OVERHAUL { get; set; }
        public string ACS_SPT_TEST { get; set; }
        public string ACS_LEASEDAILYFEE { get; set; }
        public string ACS_CUR_LEASEDAILYFEE { get; set; }
    }
}
