//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATIONS_MESSAGES
    {
        public long ID_APPLICATION_MESSAGE { get; set; }
        public string APPLICATION { get; set; }
        public string CODE_MESSAGE { get; set; }
        public string MESSAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SOLUTION { get; set; }
    }
}
