//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICATION()
        {
            this.ENTITY_APPLICATION_ACCESS = new HashSet<ENTITY_APPLICATION_ACCESS>();
            this.ENTITY_APPLICATION = new HashSet<ENTITY_APPLICATION>();
        }
    
        public long ID_APPLICATION { get; set; }
        public string APPLICATION_CODE { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public long FK_APPLICATION_CATEGORY { get; set; }
        public byte[] Version { get; set; }
    
        public virtual APPLICATION_CATEGORY APPLICATION_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_APPLICATION_ACCESS> ENTITY_APPLICATION_ACCESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_APPLICATION> ENTITY_APPLICATION { get; set; }
    }
}
