//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUSINESS_TYPE()
        {
            this.ENTITY = new HashSet<ENTITY>();
            this.BUSINESS_TYPE_MENUS = new HashSet<BUSINESS_TYPE_MENUS>();
        }
    
        public long ID_BUSINESS_TYPE { get; set; }
        public string CODE_BUSINESS_TYPE { get; set; }
        public string BUSINESS_TYPE1 { get; set; }
        public byte[] Version { get; set; }
        public string UK_CODE_BUSINESS_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY> ENTITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUSINESS_TYPE_MENUS> BUSINESS_TYPE_MENUS { get; set; }
    }
}
