//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS_TYPE_MENUS
    {
        public int ID_BUSINESS_TYPE_MENUS { get; set; }
        public int FK_MENUS { get; set; }
        public long FK_BUSINESS_TYPE { get; set; }
    
        public virtual BUSINESS_TYPE BUSINESS_TYPE { get; set; }
        public virtual MENUS MENUS { get; set; }
    }
}
