//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CGV()
        {
            this.ENTITY_CGV = new HashSet<ENTITY_CGV>();
        }
    
        public int ID_CGV { get; set; }
        public string CODE_CGV { get; set; }
        public string LABEL_CGV { get; set; }
        public Nullable<System.DateTime> PUBLICATION_DATE_CGV { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE_CGV { get; set; }
        public string URL_CGV { get; set; }
        public string FILENAME_CGV { get; set; }
        public Nullable<int> FILESIZE_CGV { get; set; }
        public byte[] FILECONTENT_CGV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_CGV> ENTITY_CGV { get; set; }
    }
}
