//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTS_ATR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACTS_ATR()
        {
            this.ENTITY_CONTACTS_ATR = new HashSet<ENTITY_CONTACTS_ATR>();
        }
    
        public int ID_CONTACT { get; set; }
        public string PREFIX { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public byte[] PICTURE { get; set; }
        public int FK_CONTACT_TYPE { get; set; }
        public byte[] Version { get; set; }
    
        public virtual CONTACT_TYPE CONTACT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_CONTACTS_ATR> ENTITY_CONTACTS_ATR { get; set; }
    }
}
