//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_CPY_SUPPORT_CENTER
    {
        public int ID { get; set; }
        public decimal CPY_NRID { get; set; }
        public string CPY_SUPPORT_CENTER { get; set; }
        public string CPY_NAME { get; set; }
    }
}
