//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PORTAL_MANAGEMENT
    {
        public int ID { get; set; }
        public string TYPE_NAME { get; set; }
        public string THEME { get; set; }
        public string PORTAL_MNGT_OPTION { get; set; }
        public string EMAIL_TLS { get; set; }
        public string EMAIL_AES { get; set; }
        public string EMAIL_AICS { get; set; }
        public string EMAIL_AAS { get; set; }
        public Nullable<int> AOG_AVAILABLE { get; set; }
        public Nullable<int> AOG_DELAY_HOURS { get; set; }
        public Nullable<int> CRITICAL_AVAILABLE { get; set; }
        public Nullable<int> CRITICAL_DELAY_HOURS { get; set; }
        public Nullable<int> ROUTINE_AVAILABLE { get; set; }
        public Nullable<int> ROUTINE_DELAY_HOURS { get; set; }
    }
}
