//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PORTAL_MESSAGES
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string MESSAGEVALUE { get; set; }
        public byte[] Version { get; set; }
    }
}
