//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATION> APPLICATION { get; set; }
        public virtual DbSet<APPLICATION_CATEGORY> APPLICATION_CATEGORY { get; set; }
        public virtual DbSet<BUSINESS_TYPE> BUSINESS_TYPE { get; set; }
        public virtual DbSet<CONTACT_TYPE> CONTACT_TYPE { get; set; }
        public virtual DbSet<CONTACTS_ATR> CONTACTS_ATR { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<CRM_ATA> CRM_ATA { get; set; }
        public virtual DbSet<CRM_CPY_SUPPORT_CENTER> CRM_CPY_SUPPORT_CENTER { get; set; }
        public virtual DbSet<CRM_MSN> CRM_MSN { get; set; }
        public virtual DbSet<CRM_PORTAL_MANAGEMENT> CRM_PORTAL_MANAGEMENT { get; set; }
        public virtual DbSet<CRM_PORTAL_MESSAGES> CRM_PORTAL_MESSAGES { get; set; }
        public virtual DbSet<CURRENCIES> CURRENCIES { get; set; }
        public virtual DbSet<ENTITES_NEW_APPLICATIONS> ENTITES_NEW_APPLICATIONS { get; set; }
        public virtual DbSet<ENTITES_RIGHTS> ENTITES_RIGHTS { get; set; }
        public virtual DbSet<ENTITES_WAREHOUSE> ENTITES_WAREHOUSE { get; set; }
        public virtual DbSet<ENTITY> ENTITY { get; set; }
        public virtual DbSet<ENTITY_APPLICATION> ENTITY_APPLICATION { get; set; }
        public virtual DbSet<ENTITY_APPLICATION_ACCESS> ENTITY_APPLICATION_ACCESS { get; set; }
        public virtual DbSet<ENTITY_CONTACTS_ATR> ENTITY_CONTACTS_ATR { get; set; }
        public virtual DbSet<FREQUENCIES> FREQUENCIES { get; set; }
        public virtual DbSet<HISTO_LOGIN_USERS> HISTO_LOGIN_USERS { get; set; }
        public virtual DbSet<JOB_PROFIL> JOB_PROFIL { get; set; }
        public virtual DbSet<NEW_APPLICATIONS> NEW_APPLICATIONS { get; set; }
        public virtual DbSet<NOTIFICATIONS> NOTIFICATIONS { get; set; }
        public virtual DbSet<PARAMETERS> PARAMETERS { get; set; }
        public virtual DbSet<RIGHT_LEVELS> RIGHT_LEVELS { get; set; }
        public virtual DbSet<RIGHTS> RIGHTS { get; set; }
        public virtual DbSet<SUBSCRIBE> SUBSCRIBE { get; set; }
        public virtual DbSet<SUPPORT_CENTER> SUPPORT_CENTER { get; set; }
        public virtual DbSet<TRAINING_CENTER> TRAINING_CENTER { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<USERS_NEW_APPLICATIONS> USERS_NEW_APPLICATIONS { get; set; }
        public virtual DbSet<USERS_RIGHTS> USERS_RIGHTS { get; set; }
        public virtual DbSet<WAREHOUSES> WAREHOUSES { get; set; }
        public virtual DbSet<ACS_PDF_FILE> ACS_PDF_FILE { get; set; }
        public virtual DbSet<ACS_ZONE2> ACS_ZONE2 { get; set; }
        public virtual DbSet<GSE_ZONE> GSE_ZONE { get; set; }
        public virtual DbSet<vw_extract_administrators_entity> vw_extract_administrators_entity { get; set; }
        public virtual DbSet<vw_extract_applications_columns> vw_extract_applications_columns { get; set; }
        public virtual DbSet<vw_extract_applications_entity> vw_extract_applications_entity { get; set; }
        public virtual DbSet<vw_extract_contacts_entity> vw_extract_contacts_entity { get; set; }
        public virtual DbSet<vw_extract_new_applications_entity> vw_extract_new_applications_entity { get; set; }
        public virtual DbSet<vw_extract_new_applications_entity_columns> vw_extract_new_applications_entity_columns { get; set; }
        public virtual DbSet<vw_extract_new_applications_user> vw_extract_new_applications_user { get; set; }
        public virtual DbSet<vw_extract_new_applications_user_columns> vw_extract_new_applications_user_columns { get; set; }
        public virtual DbSet<vw_extract_request_warranty_notification_user> vw_extract_request_warranty_notification_user { get; set; }
        public virtual DbSet<vw_extract_warehouse_entity> vw_extract_warehouse_entity { get; set; }
        public virtual DbSet<vw_extract_warehouse_types> vw_extract_warehouse_types { get; set; }
        public virtual DbSet<BUSINESS_TYPE_MENUS> BUSINESS_TYPE_MENUS { get; set; }
        public virtual DbSet<MENUS> MENUS { get; set; }
        public virtual DbSet<APPLICATIONS_MESSAGES> APPLICATIONS_MESSAGES { get; set; }
        public virtual DbSet<ENTITY_TCU> ENTITY_TCU { get; set; }
        public virtual DbSet<TCU> TCU { get; set; }
        public virtual DbSet<CGV> CGV { get; set; }
        public virtual DbSet<ENTITY_CGV> ENTITY_CGV { get; set; }
    
        public virtual int usp_extract_all_entities(Nullable<int> entity_id)
        {
            var entity_idParameter = entity_id.HasValue ?
                new ObjectParameter("entity_id", entity_id) :
                new ObjectParameter("entity_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_extract_all_entities", entity_idParameter);
        }
    
        public virtual int usp_extract_entities(Nullable<int> entity_id)
        {
            var entity_idParameter = entity_id.HasValue ?
                new ObjectParameter("entity_id", entity_id) :
                new ObjectParameter("entity_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_extract_entities", entity_idParameter);
        }
    
        public virtual int usp_extract_users(Nullable<int> entity_id)
        {
            var entity_idParameter = entity_id.HasValue ?
                new ObjectParameter("entity_id", entity_id) :
                new ObjectParameter("entity_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_extract_users", entity_idParameter);
        }
    
        public virtual ObjectResult<usp_extract_tcu_cgv_Result> usp_extract_tcu_cgv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_extract_tcu_cgv_Result>("usp_extract_tcu_cgv");
        }
    }
}
