//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTITY()
        {
            this.ENTITES_NEW_APPLICATIONS = new HashSet<ENTITES_NEW_APPLICATIONS>();
            this.ENTITES_RIGHTS = new HashSet<ENTITES_RIGHTS>();
            this.ENTITES_WAREHOUSE = new HashSet<ENTITES_WAREHOUSE>();
            this.ENTITY_APPLICATION_ACCESS = new HashSet<ENTITY_APPLICATION_ACCESS>();
            this.ENTITY_APPLICATION = new HashSet<ENTITY_APPLICATION>();
            this.ENTITY_CONTACTS_ATR = new HashSet<ENTITY_CONTACTS_ATR>();
            this.USERS = new HashSet<USERS>();
            this.ENTITY_TCU = new HashSet<ENTITY_TCU>();
            this.ENTITY_CGV = new HashSet<ENTITY_CGV>();
        }
    
        public int ID_ENTITY { get; set; }
        public string SUBSCRIPTION_STATUS { get; set; }
        public Nullable<bool> E_SPARE_CGV { get; set; }
        public Nullable<System.DateTime> E_SPARE_CGV_DATE { get; set; }
        public Nullable<System.DateTime> SUBSCRIPTION_DATE { get; set; }
        public Nullable<System.DateTime> ACTIVATION_DATE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string URL_WEBSITE { get; set; }
        public string COMPANY_DESCRIPTION { get; set; }
        public bool PORTAL_TC { get; set; }
        public string ATR_CODE { get; set; }
        public byte[] ENTITY_LOGO { get; set; }
        public Nullable<bool> PUBLIC_ENTITY { get; set; }
        public bool IS_GMA { get; set; }
        public Nullable<int> FK_SUPPORT_CENTER { get; set; }
        public Nullable<long> FK_TRAINING_CENTER { get; set; }
        public long FK_BUSINESS_TYPE { get; set; }
        public Nullable<int> FK_COUNTRY { get; set; }
        public byte[] Version { get; set; }
        public string UK_ATR_CODE { get; set; }
        public bool CIB_ACCESS { get; set; }
        public string COMPANY_MAIL { get; set; }
        public string CIN { get; set; }
        public Nullable<System.DateTime> VALIDITY_END_DATE { get; set; }
        public Nullable<System.DateTime> SUBSCRIPTION_DATE2 { get; set; }
        public Nullable<long> FK_CURRENCY { get; set; }
        public bool FLIGHT_OPS_DOC_LIMITED_ACCESS { get; set; }
    
        public virtual BUSINESS_TYPE BUSINESS_TYPE { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual CURRENCIES CURRENCIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITES_NEW_APPLICATIONS> ENTITES_NEW_APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITES_RIGHTS> ENTITES_RIGHTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITES_WAREHOUSE> ENTITES_WAREHOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_APPLICATION_ACCESS> ENTITY_APPLICATION_ACCESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_APPLICATION> ENTITY_APPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_CONTACTS_ATR> ENTITY_CONTACTS_ATR { get; set; }
        public virtual SUPPORT_CENTER SUPPORT_CENTER { get; set; }
        public virtual TRAINING_CENTER TRAINING_CENTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS> USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_TCU> ENTITY_TCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_CGV> ENTITY_CGV { get; set; }
    }
}
