//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITY_CONTACTS_ATR
    {
        public int FK_ENTITY { get; set; }
        public int FK_CONTACTS_ATR { get; set; }
        public byte[] Version { get; set; }
    
        public virtual CONTACTS_ATR CONTACTS_ATR { get; set; }
        public virtual ENTITY ENTITY { get; set; }
    }
}
