//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITES_NEW_APPLICATIONS
    {
        public long ID_ENTITES_NEW_APPLICATIONS { get; set; }
        public string CODE_ENTITY { get; set; }
        public bool ACCESS { get; set; }
        public long FK_NEW_APPLICATIONS { get; set; }
        public int FK_ENTITY { get; set; }
    
        public virtual ENTITY ENTITY { get; set; }
        public virtual NEW_APPLICATIONS NEW_APPLICATIONS { get; set; }
    }
}
