//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSE_ZONE
    {
        public string GSE_NUMPN { get; set; }
        public string GSE_LIB { get; set; }
        public string GSE_REMARK { get; set; }
        public string GSE_TEST { get; set; }
        public string GSE_CALIBRATION { get; set; }
        public string GSE_TEST_UP_LEASE { get; set; }
        public string GSE_ZONE1 { get; set; }
        public string GSE_NOMFIC { get; set; }
    }
}
