//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENUS()
        {
            this.BUSINESS_TYPE_MENUS = new HashSet<BUSINESS_TYPE_MENUS>();
        }
    
        public int ID_MENU { get; set; }
        public string CODE_MENU { get; set; }
        public string LABEL_MENU { get; set; }
        public string DESCRIPTION_MENU { get; set; }
        public string URL_MENU { get; set; }
        public string TYPE_MENU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUSINESS_TYPE_MENUS> BUSINESS_TYPE_MENUS { get; set; }
    }
}
