//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW_APPLICATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NEW_APPLICATIONS()
        {
            this.ENTITES_NEW_APPLICATIONS = new HashSet<ENTITES_NEW_APPLICATIONS>();
            this.FREQUENCIES = new HashSet<FREQUENCIES>();
            this.NOTIFICATIONS = new HashSet<NOTIFICATIONS>();
            this.USERS_NEW_APPLICATIONS = new HashSet<USERS_NEW_APPLICATIONS>();
            this.RIGHTS = new HashSet<RIGHTS>();
        }
    
        public long ID_NEW_APPLICATION { get; set; }
        public string CODE_NEW_APPLICATION { get; set; }
        public string LABEL_NEW_APPLICATION { get; set; }
        public long FK_APPLICATION_CATEGORY { get; set; }
        public long FK_RIGHT_LEVEL { get; set; }
        public string DESCRIPTION_NEW_APPLICATION { get; set; }
        public string URL_NEW_APPLICATION { get; set; }
        public bool IS_ENABLED { get; set; }
    
        public virtual APPLICATION_CATEGORY APPLICATION_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITES_NEW_APPLICATIONS> ENTITES_NEW_APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FREQUENCIES> FREQUENCIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATIONS> NOTIFICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_NEW_APPLICATIONS> USERS_NEW_APPLICATIONS { get; set; }
        public virtual RIGHT_LEVELS RIGHT_LEVELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIGHTS> RIGHTS { get; set; }
    }
}
