//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIGHT_LEVELS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RIGHT_LEVELS()
        {
            this.NEW_APPLICATIONS = new HashSet<NEW_APPLICATIONS>();
        }
    
        public long ID_RIGHT_LEVEL { get; set; }
        public string CODE_RIGHT_LEVEL { get; set; }
        public string LABEL_RIGHT_LEVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEW_APPLICATIONS> NEW_APPLICATIONS { get; set; }
    }
}
