//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIGHTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RIGHTS()
        {
            this.ENTITES_RIGHTS = new HashSet<ENTITES_RIGHTS>();
            this.USERS_RIGHTS = new HashSet<USERS_RIGHTS>();
        }
    
        public long ID_RIGHT { get; set; }
        public string CODE_RIGHT { get; set; }
        public string LABEL_RIGHT { get; set; }
        public string DESCRIPTION_RIGHTS { get; set; }
        public long FK_NEW_APPLICATIONS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITES_RIGHTS> ENTITES_RIGHTS { get; set; }
        public virtual NEW_APPLICATIONS NEW_APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_RIGHTS> USERS_RIGHTS { get; set; }
    }
}
