//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBE
    {
        public long ID_SUBSCRIBE { get; set; }
        public long FK_USERS { get; set; }
        public long FK_NOTIFICATIONS { get; set; }
        public long FK_FREQUENCIES { get; set; }
    
        public virtual FREQUENCIES FREQUENCIES { get; set; }
        public virtual NOTIFICATIONS NOTIFICATIONS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
