//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORT_CENTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPORT_CENTER()
        {
            this.ENTITY = new HashSet<ENTITY>();
        }
    
        public int ID_SUPPORT_CENTER { get; set; }
        public string SUPPORT_CENTER_NAME { get; set; }
        public string TELEPHONE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string CODE { get; set; }
        public string AOG_EMAIL { get; set; }
        public string SparesOrders_EMAIL { get; set; }
        public string Commercial_EMAIL { get; set; }
        public string SparesQuotation_EMAIL { get; set; }
        public string TeckDesk_EMAIL { get; set; }
        public string Warranty_EMAIL { get; set; }
        public byte[] Version { get; set; }
        public string VENDOR_MONITORING_EMAIL { get; set; }
        public string CentreCRM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY> ENTITY { get; set; }
    }
}
