//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCU()
        {
            this.ENTITY_TCU = new HashSet<ENTITY_TCU>();
        }
    
        public int ID_TCU { get; set; }
        public string CODE_TCU { get; set; }
        public string LABEL_TCU { get; set; }
        public Nullable<System.DateTime> PUBLICATION_DATE_TCU { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE_TCU { get; set; }
        public string URL_TCU { get; set; }
        public string FILENAME_TCU { get; set; }
        public Nullable<int> FILESIZE_TCU { get; set; }
        public byte[] FILECONTENT_TCU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY_TCU> ENTITY_TCU { get; set; }
    }
}
