//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_CENTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAINING_CENTER()
        {
            this.ENTITY = new HashSet<ENTITY>();
        }
    
        public long ID_TRAINING_CENTER { get; set; }
        public string TRAINING_CENTER1 { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string SALES_EMAIL { get; set; }
        public string PLANNING_EMAIL { get; set; }
        public string RECEPTION_EMAIL { get; set; }
        public string OTHER_EMAIL { get; set; }
        public byte[] Version { get; set; }
        public string UK_SALES_EMAIL { get; set; }
        public string UK_PLANNING_EMAIL { get; set; }
        public string UK_RECEPTION_EMAIL { get; set; }
        public string UK_OTHER_EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITY> ENTITY { get; set; }
    }
}
