//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.SUBSCRIBE = new HashSet<SUBSCRIBE>();
            this.USERS_NEW_APPLICATIONS = new HashSet<USERS_NEW_APPLICATIONS>();
            this.USERS_RIGHTS = new HashSet<USERS_RIGHTS>();
        }
    
        public long ID_USER { get; set; }
        public string PREFIX { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string SUBSCRIPTION_STATUS { get; set; }
        public string USER_LOGIN { get; set; }
        public bool E_SPARES_ACCESS { get; set; }
        public string INTERNAL_LOGIN { get; set; }
        public string INTERNAL_PASSWORD { get; set; }
        public string AD_ACCOUNT { get; set; }
        public Nullable<bool> INTERNAL_USER { get; set; }
        public bool IS_ADMINISTRATOR { get; set; }
        public Nullable<System.DateTime> LAST_CONNEXION_DATE { get; set; }
        public int FK_ENTITY { get; set; }
        public Nullable<long> FK_JOB_PROFIL { get; set; }
        public Nullable<int> FK_COUNTRY { get; set; }
        public byte[] Version { get; set; }
        public string UK_INTERNAL_LOGIN { get; set; }
        public string UK_AD_ACCOUNT { get; set; }
        public string JOB_TITLE { get; set; }
        public bool TALK_INITIATORS_EM { get; set; }
        public bool TALK_INITIATORS_FOPS { get; set; }
        public Nullable<bool> MY_REQUESTS_FOLLOWUP_ACCESS { get; set; }
        public Nullable<System.DateTime> SUBSCRIPTION_DATE { get; set; }
        public Nullable<bool> MY_WARRANTY_STATUS_ACCESS { get; set; }
        public Nullable<bool> FREQUENCY { get; set; }
        public Nullable<bool> REQUEST_CREATED { get; set; }
        public Nullable<bool> REQUEST_ANSWERED { get; set; }
        public Nullable<bool> WARRANTY_CREATED { get; set; }
        public Nullable<bool> WARRANTY_ANSWERED { get; set; }
        public Nullable<bool> INTERACTION_WITH_ATR { get; set; }
        public Nullable<bool> IS_ADMIN_ATR_CRM { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ENTITY ENTITY { get; set; }
        public virtual JOB_PROFIL JOB_PROFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBSCRIBE> SUBSCRIBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_NEW_APPLICATIONS> USERS_NEW_APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_RIGHTS> USERS_RIGHTS { get; set; }
    }
}
