//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_extract_contacts_entity
    {
        public int ID_ENTITY { get; set; }
        public int ID_CONTACT_TYPE { get; set; }
        public string CONTACT_TYPE { get; set; }
        public string contacts { get; set; }
    }
}
