//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    public partial class vw_extract_request_warranty_notification_user
    {
        public long ID_USER { get; set; }
        public string notifications_request { get; set; }
        public string notifications_warranty { get; set; }
    }
}
