//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    public partial class vw_extract_new_applications_user_columns
    {
        public long ID_NEW_APPLICATION { get; set; }
        public string CODE_NEW_APPLICATION { get; set; }
        public int column_type { get; set; }
        public string column_header { get; set; }
    }
}
