//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATR.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSES()
        {
            this.ENTITES_WAREHOUSE = new HashSet<ENTITES_WAREHOUSE>();
        }
    
        public long ID_WAREHOUSES { get; set; }
        public string CODE_WAREHOUSES { get; set; }
        public string LABEL_WAREHOUSES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITES_WAREHOUSE> ENTITES_WAREHOUSE { get; set; }
    }
}
